### ISSUE TITLE
Support multiple CORS origins for sync subscriptions

### ISSUE THREAD

**Issue by brianneisler** [serverless/event-gateway#16]
# This is a Feature Request

Ideally the gateway would support multiple headers to be configured, and perform a request-time match for us returning only one CORS header since only one is supported by W3C https://www.w3.org/TR/cors/#resource-requests.

```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/create
          method: get
          cors:
            origins:
              - https://origin1.com
              - https://origin2.com
```

Related issue from framework https://github.com/serverless/serverless/issues/2476
