### ISSUE TITLE
Deploying errors when subscribing to dynamodb stream 

### ISSUE THREAD

**Issue by johnlim** [serverless/event-gateway#499]
## This is a Bug Report
In my serverless.yml, if I subscribe to a dynamodb stream as follows:

My serverless.yml is as follows:
```
service: userMicroservice

app: usermicroservice
tenant: xxxxx

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  main:
    handler: handler.main
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /
          method: GET
  users:
    handler: handler.users
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /users
          method: POST

  eventstore:
    handler: handler.eventStore
    events:
      - stream:
           type: dynamodb
           arn:
             Fn::GetAtt:
               - UserEventStore
               - StreamArn

custom:
  eventTypes:
    http.request:

resources:
  Resources:
    UserEventStore:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain # Retain = does not remove the db when sls remove is invoked
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        StreamSpecification:
                  StreamViewType: NEW_IMAGE

plugins:
  - "@serverless/serverless-event-gateway-plugin"

```
I'll get the following error below
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (9.76 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Service Information
service: userMicroservice
stage: dev
region: us-east-1
stack: userMicroservice-dev
api keys:
  None
endpoints:
  None
functions:
  main: userMicroservice-dev-main
  users: userMicroservice-dev-users
  eventstore: userMicroservice-dev-eventstore

Event Gateway Plugin
Serverless: Removing old service artifacts from S3...
Serverless: Publishing service to Serverless Platform...
 
  Error --------------------------------------------------
 
  {"errorMessage":"Something went wrong. Please try again in a minute. - Error id: 8a47a979-00a7-45ab-9c66-ff60073d6358"}
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.30.0
```
Full log with SLS_DEBUG switched ON
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command gateway
Serverless: Load command gateway:emit
Serverless: Load command gateway:dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Service files not changed. Skipping deployment...
Serverless: Invoke aws:info
Service Information
service: userMicroservice
stage: dev
region: us-east-1
stack: userMicroservice-dev
api keys:
  None
endpoints:
  None
functions:
  main: userMicroservice-dev-main
  users: userMicroservice-dev-users
  eventstore: userMicroservice-dev-eventstore

Event Gateway Plugin
Serverless: WARNING: Inappropriate call of provider.request()
Serverless: Invoke aws:deploy:finalize

```

**Comment by johnlim** [comment]
Update: The following portion is causing the deployment errors
```
eventstore:
    handler: handler.eventStore
    events:
      - stream:
           type: dynamodb
           arn:
             Fn::GetAtt:
               - UserEventStore
               - StreamArn
```
if I modify it to use the arn string directly like so
```
eventstore:
    handler: handler.eventStore
    events:
      - stream:arn:aws:dynamodb:xxxx:table/userMicroservice-dev/stream/2018-08-13T09:45:09.675
```
then I do not encounter any deployment errors.
