### ISSUE TITLE
http.request type is not found.

### ISSUE THREAD

**Issue by lexxito** [serverless/event-gateway#512]
Good day! 

Currently, I am trying to run [tutorial](https://github.com/kelseyhightower/event-gateway-on-kubernetes ) with the newest version of the event-gateway using minikube. This tutorial doesn't work for me when I try to create a subscription: 

```
curl -k --request POST \
  --url https://minikube_ip:4001/config/v1/spaces/default/subscriptions \
  --header 'content-type: application/json' \
  --data '{ "type": "sync",
            "eventType": "http.request",
            "functionId": "hello-serverless-kubeless",
            "method": "POST",
            "path": "/hello-serverless-kubeless"}'
```

I get an error: 

`{"errors":[{"message":"Event Type \"http.request\" not found."}]}`

here is yaml file to deploy event-gateway:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-event-gateway
  labels:
    app: serverless-event-gateway
spec:
  selector:
    matchLabels:
      app: serverless-event-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: serverless-event-gateway
    spec:
      containers:
        - name: serverless-event-gateway
          image: serverless/event-gateway:0.9.1
          args:
            - "-db-hosts=etcd-event-gateway:2379"
            - "-log-format=text"
            - "-log-level=debug"
          livenessProbe:
            httpGet:
              path: "/v1/status"
              port: 4001
          readinessProbe:
            httpGet:
              path: "/v1/status"
              port: 4001

apiVersion: v1
kind: Service
metadata:
  name: serverless-event-gateway
spec:
  type: ClusterIP
  ports:
    - name: events
      protocol: TCP
      port: 4000
    - name: config
      protocol: TCP
      port: 4001
  selector:
    app: serverless-event-gateway
```

I would be super thankful if you have an idea why the build in type is not recognizable in my case.

best,
Oleksii
